mysite/CRUD/urls.py
from django.contrib import admin
from django.urls import path 
from . import views

urlpatterns = [
    path('admin',  admin.site.urls),
    path('', views.INDEX, name = 'home'),
    path('csvfiles', views.showallCSV, name ="csvfiles" ),
    path('csv/<str:id>', views.showaCsv, name ="showaCsv" ),
    path('add', views.ADD, name = 'add'),
    path('edit', views.EDIT, name = 'edit'),
    path('update/<str:id>', views.UPDATE   , name = 'update'),
    path('updatecsv/<str:id>', views.UPDATECSV   , name = 'updatecsv'),
    path('delete/<str:id>', views.DELETE   , name = 'delete'),
    path('deletecsv/<str:id>', views.DELETECSV   , name = 'deletecsv'),
    path('seegraph/<str:id>', views.runSarimaView, name = 'seegraph'),
    path('sarimaAnalysis/<str:id>', views.runSarimaAnalysis, name = "sarimaAnalysis"),
    path('varPlot/<str:id>', views.varDifPlot, name = "sarimaAnalysis")

]




handler404 = 'CRUD.views.error_404_view'

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('upload/', include(('csvs.urls', 'csvs'),namespace='csvs')),
    path('', include(('CRUD.urls', 'CRUD'), namespace='CRUD')),
]
from django.contrib import admin
from django.urls import include, path

# add the following path in the
# url patterns


# add a flag for
# handling the 404 error

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/CRUD/models.py
from django.db import models

# Create your models here.

mysite/CRUD/views.py
from itertools import product
import statsmodels.api as sm
from io import StringIO
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.tsa.stattools import kpss
import statsmodels.api as sm 
from tqdm import tqdm

from dateutil.relativedelta import relativedelta
from datetime import datetime as dt
from django.shortcuts import render
from polls.models import Sale
from django.shortcuts import redirect
from csvs.models import Csv
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import csv

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import warnings
warnings.filterwarnings('ignore')
# from runSarima import runSarimafff
# Create your views here.
 
def error_404_view(request, exception):
   
    # we add the path to the 404.html file
    # here. The name of our HTML file is 404.html
    return render(request, '404.html')
# @login_required(redirect("accounts:login"))
@login_required(login_url="/accounts/login/")
def INDEX(request):
    sale = Sale.objects.all()
    context = {
        'sale': sale,
    }
    return render(request, 'CRUD/index.html', context)




@login_required(login_url="/accounts/login/")
def ADD(request):
    if (request.method == 'POST'):
        print(request)
        prod_desc = request.POST.get('prod_desc')
        cost = request.POST.get('cost')
        date_of_pur = request.POST.get('date_of_pur')

        sale = Sale.objects.create(
            prod_desc=prod_desc,
            cost=cost,
            date_of_pur=date_of_pur
        )

        sale.save()
        return redirect('CRUD:home')
    sale = Sale.objects.all()
    context = {
        'sale': sale,
    }
    return render(request, 'CRUD/index.html', context)


@login_required(login_url="/accounts/login/")
def EDIT(request):

    sale = Sale.objects.all()
    print(type(sale[0].date_of_pur))
    context = {
        'sale': sale,
    }
    return render(request, 'CRUD/index.html', context)


@login_required(login_url="/accounts/login/")
def UPDATE(request, id):
    if (request.method == 'POST'):
        prod_desc = request.POST.get('prod_desc')
        cost = request.POST.get('cost')
        date_of_pur = request.POST.get('date_of_pur')
        sale = Sale(
            id=id,
            prod_desc=prod_desc,
            cost=cost,
            date_of_pur=date_of_pur
        )
        sale.save()
        return redirect('CRUD:home')
    sale = Sale.objects.all()
    context = {
        'sale': sale,
    }
    return render(request, 'CRUD/index.html', context)


@login_required(login_url="/accounts/login/")
def DELETE(request, id):
    sale = Sale.objects.filter(id=id).delete()
    return redirect('CRUD:home')


@login_required(login_url="/accounts/login/")
def UPDATECSV(request, id):
    csv = Csv.objects.filter(id=id).update(activated=True)
    return redirect('CRUD:csvfiles')


@login_required(login_url="/accounts/login/")
def DELETECSV(request, id):
    csv = Csv.objects.filter(id=id).delete()
    return redirect('CRUD:csvfiles')

@login_required(login_url="/accounts/login/")
def showaCsv(request, id):
    print(id)
    tmpcsv = Csv.objects.filter(id=id).first()
    print(tmpcsv)
    filename = tmpcsv.file_name.path
    print(filename)
    filedata = []
    header = []
    with open(filename, 'r') as f:
        print(f)
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i == 0:
                header = row

            else:
                filedata.append(row)
    context = {
        "filedata": filedata,
        "header": header,
        "id": id
    }
    return render(request, 'CRUD/showacsv.html', context)


@login_required(login_url="/accounts/login/")
def showallCSV(request):
    csvs = Csv.objects.all()
    filesdata = []
    for obj in csvs.iterator():
        tmpobj = {
            "id": obj.id,
            "filename": obj.file_name,
            "fileUploadDateTime": obj.uploaded,
            "activated": obj.activated,
            "path": obj.file_name.path,
        }
        filesdata.append(tmpobj)
    context = {
        "filesData": filesdata
    }
    return render(request, 'CRUD/showallCSV.html', context)

# From here our main work will start that is analysing a CSV file using the time series algorithm
# We will use SARIMA algorithm for this purpose

def Basic_dataGraph(data):
    fig = plt.figure(figsize=[8, 6])  # Set dimensions for figure
    plt.plot(data['date'], data['data'])
    plt.title('Quarterly EPS for Johnson & Johnson')
    plt.ylabel('EPS per share ($)')
    plt.xlabel('Date')
    plt.xticks(rotation=90)
    plt.grid(True)
    imgdata = StringIO()

    fig.savefig(imgdata, format='svg')
    imgdata.seek(0)
    data = imgdata.getvalue()
    return data


def acf_plot(data):
    fig, ax = plt.subplots(1,2,figsize=(10,5))
    sm.graphics.tsa.plot_pacf(data['data'].values.squeeze(), lags=10, ax=ax[0])
    sm.graphics.tsa.plot_acf(data['data'].values.squeeze(), lags=10, ax=ax[1])
    plt.plot()
    imgdata = StringIO()
    fig.savefig(imgdata, format='svg')
    imgdata.seek(0)
    data2 = imgdata.getvalue()
    return data2

def kpss_test(timeseries):
    result = {}
    print ('Results of KPSS Test:')
    kpsstest = kpss(timeseries, regression='c')
    kpss_output = pd.Series(kpsstest[0:3], index=['Test Statistic','p-value','Lags Used'])
    for key,value in kpsstest[3].items():
      kpss_output['Critical Value (%s)'%key] = value
    return kpss_output

# de fresults before the actual analysis
def log_dif_plot(data, dif =1):
    data['log_data'] = np.log(data['data'])
    data['log_dif_data'] = data['log_data'].diff(int(dif))
    data = data.iloc[int(dif):]
    fig = plt.figure(figsize=[8, 6]); # Set dimensions for figure
    plt.plot(data['log_dif_data'])
    plt.title("Log Difference of Quarterly EPS for Johnson & Johnson")
    # plt.plot()
    imgdata = StringIO()

    fig.savefig(imgdata, format='svg')
    imgdata.seek(0)
    data1 = imgdata.getvalue()

    fig, ax = plt.subplots(1,2,figsize=(10,5))
    sm.graphics.tsa.plot_pacf(data['log_dif_data'].values.squeeze(), lags=10, ax=ax[0])
    sm.graphics.tsa.plot_acf(data['log_dif_data'].values.squeeze(), lags=10, ax=ax[1])
    plt.plot()
    imgdata = StringIO()
    fig.savefig(imgdata, format='svg')
    imgdata.seek(0)
    data2 = imgdata.getvalue()
    logDif = {}
    logDif['acf'] = data2
    logDif['basic'] = data1
    return logDif


def basic_results(data):
    # Here we will do the data visualizatikon of the data preanalysis\
    # For that here we will be doing the first the time respective plot of the data 
    # Then we will do the ACF and PACF plot of the data
    # Then we will do the KPSS and the adFuller test of the data
    # and the differentiating the data and then again doing the ACF and PACF plot of the data
    # and then again doing the KPSS and the adFuller test of the data
    
    plots = {}
    plots['basicPlot'] =Basic_dataGraph(data)
    plots['acf'] = acf_plot(data)

    plots['kpssresuult'] = kpss_test(data['data'])
    plots['adfullerresult'] = adfuller(data['data'])
    plots['log_dif_plot'] = log_dif_plot(data)

    return plots
    # then we will provide an option for user to select the differencing the data upto a certain limit and then we will show the user the graph for the user accordingly

def runSarimafff(path):
    data = pd.read_csv(path, parse_dates=['date'])
    data.head()
    basicresult = basic_results(data)
    return basicresult
    # The data visualization before the analysis is done since w eneed to get the value or the range of 
    # p q r s and P Q R S from the user after user sees the graphs and then we will run the algorithm
    # on the csv data and provide the analysis using the SARIMA algorithm


    # plots['pacf'] = pacf_plot(data)
    # return plots



@login_required(login_url="/accounts/login/")
def runSarimaView(request, id):
    print(id)
    filePath = Csv.objects.filter(id=id).first().file_name.path
    context = {}
    context['dif'] = 1
    context["id"] = id
    context['graph'] = runSarimafff(filePath)
    return render(request, 'CRUD/showGraph.html', context)


@login_required(login_url="/accounts/login/")
def varDifPlot(request, id):
    print(id)
    filePath = Csv.objects.filter(id=id).first().file_name.path
    dif = int(request.POST.get('dif'))
    context = {}
    context["id"] = id
    context['dif'] = dif
    data = pd.read_csv(filePath, parse_dates=['date'])
    plots = {}
    plots['basicPlot'] =Basic_dataGraph(data)
    plots['acf'] = acf_plot(data)

    plots['kpssresuult'] = kpss_test(data['data'])
    plots['adfullerresult'] = adfuller(data['data'])
    plots['log_dif_plot'] = log_dif_plot(data, dif)
    context['graph'] = plots
    return render(request, 'CRUD/showGraph.html', context)







def optimize_SARIMA(parameters_list, d, D, s, exog):
    """
        Return dataframe with parameters, corresponding AIC and SSE
        
        parameters_list - list with (p, q, P, Q) tuples
        d - integration order
        D - seasonal integration order
        s - length of season
        exog - the exogenous variable
    """
    
    results = []
    best_param= []
    best_aic = 10100101
    for param in tqdm(parameters_list):
        try: 
            model = SARIMAX(exog, order=(param[0], d, param[1]), seasonal_order=(param[2], D, param[3], s)).fit(disp=-1)
        except:
            continue
            
        aic = model.aic
        if(aic < best_aic):
            best_aic = aic

mysite/CRUD/templates/CRUD/index.html
{% extends "base/base1.html"%} 
<!-- {% load static %} -->
{%block start%} 
<section class="section-conten padding-y" style="min-height: 84vh">
    <div class="container">
      <div class="table-wrapper">
        <div class="table-title">
          <div class="row">
            <div class="col-sm-6">
              <h2>Manage <b>Sales Reecord</b></h2>
            </div>
            <div class="col-sm-6">
              <a
                href="#addEmployeeModal"
                class="btn btn-success"
                data-toggle="modal"
                ><i class="material-icons">&#xE147;</i>
                <span>Add New Sale Entry</span></a
              >
              <a
                href="#deleteEmployeeModal"
                class="btn btn-danger"
                data-toggle="modal"
                ><i class="material-icons">&#xE15C;</i> <span>Delete</span></a
              >
            </div>
          </div>
        </div>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>
                <span class="custom-checkbox">
                  <input type="checkbox" id="selectAll" />
                  <label for="selectAll"></label>
                </span>
              </th>

              <th>Product Description</th>
              <th>Cost</th>
              <th>Date of Purchase</th>
            </tr>
          </thead>
          <tbody>
            {% for i in sale%}
            <tr>
              <td>
                <span class="custom-checkbox">
                  <input
                    type="checkbox"
                    id="checkbox1"
                    name="options[]"
                    value="1"
                  />
                  <label for="checkbox1"></label>
                </span>
              </td>
              <td>{{i.prod_desc}}</td>
              <td>{{i.cost}}</td>
              <td>{{i.date_of_pur}}</td>
              <td>
                <a
                  href="#editEmployeeModal-{{forloop.counter}}"
                  class="edit"
                  data-toggle="modal"
                  ><i class="material-icons" data-toggle="tooltip" title="Edit"
                    >&#xE254;</i
                  ></a
                >
                <a
                  href="#deleteEmployeeModal-{{forloop.counter}}"
                  class="delete"
                  data-toggle="modal"
                  ><i
                    class="material-icons"
                    data-toggle="tooltip"
                    title="Delete"
                    >&#xE872;</i
                  ></a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div id="addEmployeeModal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <form action="{%url 'CRUD:add' %}" method="POST">
            {% csrf_token %}
            <div class="modal-header">
              <h4 class="modal-title">Add New Sale Entry</h4>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-hidden="true"
              >
                &times;
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <label>Product Description</label>
                <input
                  name="prod_desc"
                  type="text"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label>Cost</label>
                <input
                  type="number"
                  name="cost"
                  min="0"
                  value="0"
                  step=".01"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label>Date of Purchase</label>
                <input
                  type="datetime-local"
                  name="date_of_pur"
                  class="form-control"
                  required
                />
              </div>
            </div>
            <div class="modal-footer">
              <input
                type="button"
                class="btn btn-default"
                data-dismiss="modal"
                value="Cancel"
              />
              <input type="submit" class="btn btn-success" value="Add" />
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- Edit Modal HTML -->
    {% for i in sale%}
    <div id="editEmployeeModal-{{forloop.counter}}" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <form action="/update/{{i.id}}" method="post">
            {%csrf_token%}
            <div class="modal-header">
              <h4 class="modal-title">Edit Sale Record</h4>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-hidden="true"
              >
                &times;
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <label>Product Description</label>
                <input
                  value="{{i.prod_desc}}"
                  name="prod_desc"
                  type="text"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label>Cost</label>
                <input
                  type="number"
                  value="{{i.cost}}"
                  name="cost"
                  step=".01"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label>Date of Purchase</label>
                <input
                  type="datetime-local"
                  name="date_of_pur"
                  value="{{i.date_of_pur}}"
                  class="form-control"
                  required
                />
              </div>
            </div>
            <div class="modal-footer">
              <input
                type="button"
                class="btn btn-default"
                data-dismiss="modal"
                value="Cancel"
              />
              <input type="submit" class="btn btn-info" value="Update" />
            </div>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- Delete Modal HTML -->
    {% for i in sale%}
    <div id="deleteEmployeeModal-{{forloop.counter}}" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <form>
            <div class="modal-header">
              <h4 class="modal-title">Delete Sale Record</h4>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-hidden="true"
              >
                &times;
              </button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete these Records?</p>
              <p class="text-warning">
                <small>This action cannot be undone.</small>
              </p>
            </div>
            <div class="modal-footer">
              <input
                type="button"
                class="btn btn-default"
                data-dismiss="modal"
                value="Cancel"
              />
              <a href="/delete/{{i.id}}" type="submit" class="btn btn-danger"
                >Delete</a
              >
            </div>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
    
</section>

{%endblock%}

mysite/CRUD/templates/CRUD/shoeSarimaAnalysis.html
{% extends "base/base1.html"%} {%block start%}

<section class="section-conten padding-y" style="min-height: 84vh">
  <div style="display: flex; justify-content: center; align-items: center">
    {{ForecastGraph| safe }}
  </div>
  <div style="display: flex; justify-content: center; align-items: center">
    {{diagnostic| safe }}
  </div>
  <div style="display: flex; justify-content: center; align-items: center">
    <h3>The model Summary</h3>
  <p>
    {{modelSummary}}
  </p>
  </div>
  <div style="display: flex; justify-content: center; align-items: center">
    <h3>The model Summary</h3>
  <p>
    {{result_df}}
  </p>
  </div>

  <div style="display: flex; justify-content: center; align-items: center">
    <h3>The CSV result file:</h3>
  <p>
    <a href="data:text/csv;charset=utf-8,{{ csv_data }}" download="data.csv">Download CSV</a>
  </p>
  </div>
</section>

{%endblock%}

mysite/CRUD/templates/CRUD/showGraph.html
{% extends "base/base1.html"%} {%block start%}

<section class="section-conten padding-y" style="min-height: 84vh">
  <div style="display: flex; justify-content: center; align-items: center">
    {{ graph.basicPlot|safe }}
  </div>
  <div style="display: flex; justify-content: center; align-items: center">
    {{graph.acf| safe }}
  </div>
  <div>
    <h3>The AD Fuller Test Statistics:-</h3>
    <div>ADF Statistic: {{graph.adfullerresult}}</div>
  </div>
  
  <!-- <div>
    <h3>The Kpss Test Statistics:-</h3>
    <p></p>
  </div> -->
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center">
  <h2>Log Dif plots</h2>
  <div class="dropdown">
    <form action="/varPlot/{{id}}" method="post">
      {% csrf_token %}
      <label for="quantity">Log difference that you want(between 1 and 5):</label>
      <input type="number" id="dif" name="dif" min="1" max="5" value="{{dif}}">
      <input type="submit">
    </form>
  </div>
  <div style="display: flex; flex-direction: column;  justify-content: center; align-items: center">
    <h3>Basic Plot</h3>
    {{graph.log_dif_plot.basic| safe }}
  </div>
  <div style="display: flex; flex-direction: column;  justify-content: center; align-items: center">
    <h3>ACF-PACF Plot of Logarithemic Difference</h3>
    {{graph.log_dif_plot.acf| safe }}
  </div>
</div>
  <div>
    <form action="/sarimaAnalysis/{{id}} " method="POST" class="show-loading-after-submit">
      {% csrf_token %}
      <h3>Select the following parameters ranges that suits you best.</h3>
      <div style="display:inline">
        <h4>P (no. of Lags)</h4>
        <label>Start:</label>
        <input type="number" required id="quantity" name="pStart" min="0" max="5" value="1">
        <label>
          End:
        </label>
        <input type="number" required id="quantity" name="pEnd" min="0" max="5" value="5">
      </div>
      <div style="display:inline">
        <h4>Q (Size of Moving Average window)</h4>
        <label>Start:</label>
        <input type="number" required id="quantity" name="qStart" min="0" max="5" value="1">
        <label>
          End:
        </label>
        <input type="number"required  id="quantity" name="qEnd" min="0" max="5" value="5">  
      </div>
      <div style="display:inline">
        <h4>D (no. of differencing terms):</h4>
        <input type="number" required id="quantity" name="diff" min="1" max="5" value="1">
      </div>
      <div style="display:inline">
        <h4>Season:</h4>
        <input type="number" required id="quantity" name="season" min="1" max="12" value="12">
      </div>
      
      <label for="quantity">Now lets run Sarima on your database</label>
      <input type="submit">
    </form>
  </div>

</section>

{%endblock%}

mysite/CRUD/templates/CRUD/showacsv.html
{% extends "base/base1.html"%} 
<!-- {% load static %} -->
{%block start%} 

<section class="section-conten padding-y" style="min-height: 84vh">
    <div class="container">
      <div class="table-wrapper">
        <div class="table-title">
          <div class="row">
            <div class="col-sm-6">
              <h2>Manage <b>Sales Reecord</b></h2>
            </div>
            <div class="col-sm-6">
              <a
                href="#addEmployeeModal"
                class="btn btn-success"
                data-toggle="modal"
                ><i class="material-icons">&#xE147;</i>
                <span>Add New Sale Entry</span></a
              >
              <a
                href="#deleteEmployeeModal"
                class="btn btn-danger"
                data-toggle="modal"
                ><i class="material-icons">&#xE15C;</i> <span>Delete</span></a
              >
              <a
                href="#runSarima"
                class="btn btn-success"
                data-toggle="modal"
                ><i class="material-icons">&#xE147;</i>
                <span>Run Sarima on this CSV</span></a
              >
            </div>
          </div>
        </div>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>
                <span class="custom-checkbox">
                  <input type="checkbox" id="selectAll" />
                  <label for="selectAll"></label>
                </span>
              </th>
              {% for headname in header%}
              <th>{{headname}}</th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for row in filedata%}
            <tr>
              <td>
                <span class="custom-checkbox">
                  <input
                    type="checkbox"
                    id="checkbox1"
                    name="options[]"
                    value="1"
                  />
                  <label for="checkbox1"></label>
                </span>
              </td>
              {% for rowdata in row%}
              <td>{{rowdata}}</td>
              {% endfor %}
              <td>
                <a href="#" class="edit" data-toggle="modal"
                  ><i class="material-icons" data-toggle="tooltip" title="Edit"
                    >&#xE254;</i
                  ></a
                >
                <!-- <a href="#editEmployeeModal-{{forloop.counter}}" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a> -->
                <a href="#" class="delete" data-toggle="modal"
                  ><i
                    class="material-icons"
                    data-toggle="tooltip"
                    title="Delete"
                    >&#xE872;</i
                  ></a
                >
                <!-- <a href="#deleteEmployeeModal-{{forloop.counter}}" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a> -->
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- Add Modal HTML -->
    <div id="addEmployeeModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form action="{%url 'CRUD:add' %}" method="POST">
					{% csrf_token %}
					<div class="modal-header">						
						<h4 class="modal-title">Add New Sale Entry</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<div class="form-group">
							<label>Product Description</label>
							<input name = "prod_desc" type="text" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Cost</label>
							<input type="number"  name="cost" min="0" value="0" step=".01" class="form-control" required>
						</div>
						<div class="form-group">
							<label>Date of Purchase</label>
							<input type="datetime-local" name = "date_of_pur"  class="form-control" required>
						</div>				
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-success" value="Add">
					</div>
				</form>
			</div>
		</div>
	</div>
  <!-- The Sarima Running model -->
  <div id="runSarima" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form action="/seegraph/{{id}} " method="POST">
					{% csrf_token %}
					<div class="modal-header">						
						<h4 class="modal-title">Run Sarima</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-success" value="Run">
					</div>
				</form>
			</div>
		</div>
	</div>
    <!-- Edit Modal HTML -->
    {% for i in sale%}
	<div id="editEmployeeModal-{{forloop.counter}}" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form action="/update/{{i.id}}" method="post">
					{%csrf_token%}
					<div class="modal-header">						
						<h4 class="modal-title">Edit Sale Record</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">
							<div class="form-group">
								<label>Product Description</label>
								<input value="{{i.prod_desc}}" name = "prod_desc" type="text" class="form-control" required>
							</div>
							<div class="form-group">
								<label>Cost</label>
								<input type="number" value="{{i.cost}}"  name="cost"  step=".01" class="form-control" required>
							</div>
							<div class="form-group">
								<label>Date of Purchase</label>
								<input type="datetime-local" name = "date_of_pur"  value="{{i.date_of_pur}}" class="form-control" required>
							</div>				
						</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-info" value="Update">
					</div>
				</form>
			</div>
		</div>
	</div>
	{% endfor %}
    <!-- Delete Modal HTML -->
    {% for i in sale%}
	<div id="deleteEmployeeModal-{{forloop.counter}}" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form >
					<div class="modal-header">						
						<h4 class="modal-title">Delete Sale Record</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<p>Are you sure you want to delete these Records?</p>
						<p class="text-warning"><small>This action cannot be undone.</small></p>
					</div>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<a href ="/delete/{{i.id}}" type="submit" class="btn btn-danger">Delete</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	{% endfor %}
             
</section>

{%endblock%}